#!/bin/sh
# Check config file content is empty or not using cat
if [ -s /etc/config/cquauth ]; then
    echo "Config file is not empty, skip"
    exit 0
fi

touch /etc/config/cquauth
uci -q batch <<EOF
set cquauth.basic='basic'
set cquauth.basic.enabled='1'
set cquauth.basic.ping_target='223.5.5.5'
set cquauth.basic.check_interval='60'
set cquauth.basic.max_attempts='0'
set cquauth.basic.enable_ecmp='0'

add cquauth account
set cquauth.@account[-1].enabled='0'
set cquauth.@account[-1].user='20202020'
set cquauth.@account[-1].pass='123456'
set cquauth.@account[-1].interface='eth0'
set cquauth.@account[-1].ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0'
set cquauth.@account[-1].terminal_type='pc'

commit cquauth
EOF
exit 0