#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
DEPENDS="rpcd"

boot() {
    service_start /usr/sbin/rpcd -f
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/cquauth_client
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall cquauth_client
}